export default {
  user: {},
  admin_product_table_columns_header: [],
  admin_products: [],
  admin_selected_category: '',
  product_categories: [],
  selected_category: {},
  product_table_columns_header: [],
  products: [],
  filters: [],
  comparisons: [],
  filtered_results: [],
  active_filters: [],
  products_sum: {},
  current_checkbox_filter: {},
  products_sum_of_current_checkbox_filter: {},
  product_features_in_units: [],
  product_features: [],
  selected_product_feature_in_units: '',
  selected_product_feature: '',
  series_for_pie_chart: {}
}
